# Generated by Django 2.0.2 on 2018-09-07 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethod', '0003_paymentmethod_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
