# Generated by Django 2.0.2 on 2018-09-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentmethod', '0004_auto_20180907_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='color',
            field=models.CharField(default='', max_length=50),
        ),
    ]
