# Generated by Django 2.0.2 on 2018-09-07 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paymentmethod', '0003_paymentmethod_account'),
        ('location', '0003_location_account'),
        ('transactiontype', '0003_transactiontype_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_date', models.DateTimeField()),
                ('tran_amount', models.FloatField(default=0.0)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tran_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='location.Location')),
                ('tran_payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentmethod.PaymentMethod')),
                ('tran_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactiontype.TransactionType')),
            ],
        ),
    ]
