# Generated by Django 2.0.2 on 2018-09-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tran_date',
            field=models.DateField(),
        ),
    ]
